---

- name: "Install FOP package (Ubuntu >= 18.04)"
  apt:
    pkg: "fop"
    state: "latest"
  when: "ansible_distribution_version is version_compare('18.04', '>=')"
  tags:
    - "atom-fop"

- name: "Use FOP 2.1 in AtoM 2.3 or newer (Ubuntu 16.04 or RH)"
  set_fact:
    fop_version: "2.1"
  when: ( ansible_distribution_version is version('16.04', '==') ) or
    ( ansible_os_family == "RedHat" )
  tags:
    - "atom-fop"

- name: "Use FOP 1.0 in AtoM 2.2 (Ubuntu 14.04)"
  set_fact:
    fop_version: "1.0"
  when: "ansible_distribution_version is version('14.04', '==')"
  tags:
    - "atom-fop"

- name: "Install FOP from source (ubuntu <=16.04 or RH)"
  block:
    - name: "Install Apache FOP: unarchive (ubuntu <=16.04 or RH)"
      unarchive:
        src: "https://archive.apache.org/dist/xmlgraphics/fop/binaries/fop-{{ fop_version }}-bin.tar.gz"
        dest: "/usr/share"
        creates: "/usr/share/fop-{{ fop_version }}"
        copy: "no"
        owner: "root"
        group: "root"

    - name: "Install Apache FOP: set up FOP_HOME (ubuntu <=16.04 or RH)"
      lineinfile:
        dest: "/etc/environment"
        line: "FOP_HOME=/usr/share/fop-{{ fop_version }}"

    - name: "Install Apache FOP: symlink (ubuntu <=16.04 or RH)"
      file:
        src: "/usr/share/fop-{{ fop_version }}/fop"
        dest: "/usr/local/bin/fop"
        state: "link"
  when: ( ansible_distribution_version is version('16.04', '<=') ) or
          ( ansible_os_family == "RedHat" )
  tags:
      - "atom-fop"


- name: "Allow pdfs to be converted by ImageMagick (Ubuntu)"
  lineinfile:
    path: "/etc/ImageMagick-6/policy.xml"
    state: "absent"
    regexp: 'PDF" />$'
<<<<<<< HEAD
  when: "ansible_distribution_version is version('16.04', '>=')"

=======
  when: "ansible_distribution_version is version_compare('16.04', '>=')"
>>>>>>> 2bdecaf... AtoM on Ubuntu 20.04
