---

# stdout is ignored, not very useful and too verbose (--quiet opt would be nice)
- name: "Populate search index"
  shell: "php symfony search:populate 1>/dev/null"
  args:
    chdir: "{{ atom_path }}"
  ignore_errors: "yes" # segfault in php7, not sure yet why!
  environment: "{{ atom_pool_php_envs }}"
