---

- name: "Uploads symlink"
  file:
    state: "link"
    src: "{{ atom_uploads_symlink }}"
    path: "{{ atom_path }}/uploads"
    force: "yes"
    owner: "{{ atom_user }}"
    group: "{{ atom_group }}"
  when: "atom_uploads_symlink is defined"

- name: "Uploads directory"
  file:
    state: "directory"
    path: "{{ atom_path }}/uploads"
    owner: "{{ atom_user }}"
    group: "{{ atom_group }}"
  when: "atom_uploads_symlink is undefined"